config/routes.rb
Rails.application.routes.draw do

  extra_actions = Proc.new do
    collection do
      get :export
      post :import
      get :summarize
    end
  end

  namespace :kapa do
    root :to => 'user_sessions#show', :as => :root
    get '/logout' => 'user_sessions#destroy', :as => :logout
    get '/error' => 'user_sessions#error', :as => :error
    get '/cas' => 'user_sessions#cas', :as => :cas
    get 'user_session/validate' => 'user_sessions#validate'
    resource :user_session
    get 'persons/lookup(/:id)' => 'persons#lookup', :as => :persons_lookup
    get 'persons/sync(/:id)' => 'persons#sync', :as => :persons_sync
    resources :persons, &extra_actions
    resources :files, &extra_actions
    resources :forms, &extra_actions
    resources :form_templates, &extra_actions
    resources :form_template_fields, &extra_actions
    resources :texts, &extra_actions
    resources :text_templates, &extra_actions
    get 'text_templates/preview(/:id)' => 'text_templates#preview', :as => :text_templates_preview
    resources :contents, &extra_actions
    resources :properties, &extra_actions
    resources :users, &extra_actions
    resources :user_assignments, &extra_actions
  end

  #catch-all route for 404 (not found) requests
  match '*path', via: :all, to: 'application#error_404' , constraints: lambda { |request|
    !request.path.match? /^(\/rails)/
  }
end

app/models/kapa/application_property_base.rb
module Kapa::ApplicationPropertyBase
  extend ActiveSupport::Concern

  included do
    self.table_name = :properties
    validates_uniqueness_of :code, :scope => :name
    validates_presence_of :name, :code
  end

  class_methods do
    @@description_cache = HashWithIndifferentAccess.new
    @@description_detail_cache = HashWithIndifferentAccess.new
    @@category_cache = HashWithIndifferentAccess.new

    def refresh_cache
      @@description_cache.clear
      Kapa::ApplicationProperty.all.each { |v| @@description_cache["#{v.name}_#{v.code}"] = v.description }
      @@description_detail_cache.clear
      Kapa::ApplicationProperty.all.each { |v| @@description_detail_cache["#{v.name}_#{v.code}"] = v.description_short }
      @@category_cache.clear
      Kapa::ApplicationProperty.all.each { |v| @@category_cache["#{v.name}_#{v.code}"] = v.category }
    end

    def selections(options = {})
      properties = where(:active => true, :name => options[:name].to_s)
      properties = properties.depts_scope(options[:depts]) if options[:depts]
      properties = properties.where(options[:conditions]) if options[:conditions]
      properties.order("sequence DESC, description").collect do |v|
        description = ""
        description << "#{v.code}/" if options[:include_code]
        description << v.description
        [description, v.code]
      end
    end

    def lookup_description(name, code, default_value = code)
      refresh_cache if @@description_cache.empty?
      return @@description_cache["#{name}_#{code}"] ||= default_value
    end

    def lookup_description_detail(name, code, default_value = code)
      refresh_cache if @@description_detail_cache.empty?
      return @@description_detail_cache["#{name}_#{code}"] ||= default_value
    end

    def lookup_category(name, code, default_value = code)
      refresh_cache if @@category_cache.empty?
      return @@category_cache["#{name}_#{code}"] ||= default_value
    end

    def keys(name, options={})
      properties = where(:active => true, :name => options[:name].to_s)
      properties = properties.depts_scope(options[:depts]) if options[:depts]
      properties = properties.where(options[:conditions]) if options[:conditions]
      return properties.order("sequence DESC, code").collect { |v| v.code }
    end

    def append(name, code, options={})
      options[:description] = code if options[:description].blank?
      property = find_or_create_by_name_and_code(name, code)
      property.update_attributes(options)
      return property
    end

    def search(filter, options = {})
      application_properties = Kapa::ApplicationProperty.all
      application_properties = application_properties.where("name" => filter.name)  if filter.name.present?
      application_properties = application_properties.where("active" => filter.active) if filter.active.present?
      return application_properties
    end
  end
end

app/models/kapa/assessment_score_base.rb
module Kapa::AssessmentScoreBase
  extend ActiveSupport::Concern

  included do
    belongs_to :assessment_criterion
    belongs_to :assessment_scorable, :polymorphic => true
  end

  def rating_desc
    if self.assessment_criterion.type == "select" and self.assessment_criterion.type_option
      return Kapa::Property.lookup_description(assessment_criterion.type_option, self.rating)
    else
      return self.rating
    end
  end

  class_methods do
    def scores(assessment_scorables, assessment_rubric)
      #initialize table first
      scores = ActiveSupport::OrderedHash.new
      assessment_scorables.each do |s|
        assessment_rubric.active_criterions.each do |c|
          index = "#{s.id}_#{c.id}"
          scores[index] = ""
        end
      end
      #then, fill in scores using ActiveRecord cache.  this is more efficient than filing everything one by one (save SQL execution)
      self.where(:assessment_scorable_type => assessment_scorables.first.class, :assessment_scorable_id => assessment_scorables.collect {|s| s.id}).each do |score|
        index = "#{score.assessment_scorable_id}_#{score.assessment_criterion_id}"
        scores[index] = score.rating if scores[index]
      end
      return scores
    end
  end
end

app/models/kapa/bulk_message.rb
class Kapa::BulkMessage < Kapa::KapaModel
  include Kapa::BulkMessageBase
end

app/models/kapa/bulk_message_base.rb
module Kapa::BulkMessageBase
  extend ActiveSupport::Concern

  included do
    has_many :messages
    belongs_to :message_template

    after_create :set_default_contents, :replace_variables
  end

  def set_default_contents
    if self.message_template.present?
      self.name = self.message_template.title
      self.body = self.message_template.body
      self.save
    end
  end

  def replace_variables
  end

  def send_messages
    person_ids = Kapa::ContactList.where(:id => self.ext.contact_list_ids).map(&:person_ids) + self.ext.person_ids
    persons = Kapa::Person.where(:id => person_ids.flatten.uniq)
    persons.each do |person|
      message = person.messages.build(self.attributes.slice("name", "subject", "body", "message_template_id"))
      message.bulk_message = self
      message.save
    end
  end
end

app/models/kapa/calendar_event.rb
class Kapa::CalendarEvent < Kapa::KapaModel
  include Kapa::CalendarEventBase
end

app/models/kapa/calendar_event_base.rb
module Kapa::CalendarEventBase
  extend ActiveSupport::Concern

  included do
    belongs_to :person
  end
end

app/models/kapa/concerns/advising_session.rb
module Kapa::Concerns::AdvisingSession
  extend ActiveSupport::Concern

  included do
    belongs_to :person
    belongs_to :template
    has_one :contact, :as => :entity
    has_many :advising_actions
    belongs_to :user_primary,
               :class_name => "User",
               :foreign_key => "user_primary_id"
    belongs_to :user_secondary,
               :class_name => "User",
               :foreign_key => "user_secondary_id"
    validates_presence_of :person_id, :session_date, :session_type
  end # included

  def name
    if anonymous?
      return "#{identity_note}*"
    else
      return self.person.full_name
    end
  end

  def anonymous?
    return person_id == 0
  end

  module ClassMethods
    def search(filter, options = {})
      advising_sessions = Kapa::AdvisingSession.eager_load([:person => :contact])
      advising_sessions = advising_sessions.where(:session_date => filter.date_start..filter.date_end) if filter.date_start.present? and filter.date_end.present?
      advising_sessions = advising_sessions.where(:task => filter.task) if filter.task.present?
      advising_sessions = advising_sessions.where(:interest => filter.interest) if filter.interest.present?
      advising_sessions = advising_sessions.assigned_scope(filter.user_id) if filter.user_id.present?

      case filter.user.access_scope
        when 3
          # Do nothing
        when 2
          advising_sessions = advising_sessions.depts_scope(filter.user.depts)
        when 1
          advising_sessions = advising_sessions.assigned_scope(filter.user.id)
        else
          advising_sessions = advising_sessions.where("0 = 1")
      end
      return advising_sessions
    end

    def to_csv(filter, options = {})
      advising_sessions = self.search(filter).order("session_date DESC, advising_sessions.id DESC")
      CSV.generate do |csv|
        csv << self.csv_columns
        advising_sessions.each do |c|
          csv << self.csv_row(c)
        end
      end
    end

    def csv_columns
      [:id_number,
       :last_name,
       :first_name,
       :cur_street,
       :cur_city,
       :cur_state,
       :cur_postal_code,
       :cur_phone,
       :email,
       :session_date,
       :session_type,
       :task,
       :classification,
       :interest,
       :location,
       :handled_by]
    end

    def csv_row(c)
      [c.rsend(:person, :id_number),
       c.rsend(:person, :last_name),
       c.rsend(:person, :first_name),
       c.rsend(:person, :contact, :cur_street),
       c.rsend(:person, :contact, :cur_city),
       c.rsend(:person, :contact, :cur_state),
       c.rsend(:person, :contact, :cur_postal_code),
       c.rsend(:person, :contact, :cur_phone),
       c.rsend(:person, :contact, :email),
       c.rsend(:session_date),
       c.rsend(:session_type),
       c.rsend(:task),
       c.rsend(:classification),
       c.rsend(:interest),
       c.rsend(:location),
       c.rsend(:handled_by)]
    end

  end
end

app/models/kapa/concerns/application_property.rb
module Kapa::Concerns::ApplicationProperty
  extend ActiveSupport::Concern

  included do
    self.table_name = :properties
    validates_uniqueness_of :code, :scope => :name
    validates_presence_of :name, :code
  end # included

  module ClassMethods
    @@description_cache = HashWithIndifferentAccess.new
    @@description_detail_cache = HashWithIndifferentAccess.new
    @@category_cache = HashWithIndifferentAccess.new

    def refresh_cache
      @@description_cache.clear
      Kapa::ApplicationProperty.all.each { |v| @@description_cache["#{v.name}_#{v.code}"] = v.description }
      @@description_detail_cache.clear
      Kapa::ApplicationProperty.all.each { |v| @@description_detail_cache["#{v.name}_#{v.code}"] = v.description_short }
      @@category_cache.clear
      Kapa::ApplicationProperty.all.each { |v| @@category_cache["#{v.name}_#{v.code}"] = v.category }
    end

    def selections(options = {})
      properties = where(:active => true, :name => options[:name].to_s)
      properties = properties.depts_scope(options[:depts]) if options[:depts]
      properties = properties.where(options[:conditions]) if options[:conditions]
      properties.order("sequence DESC, description").collect do |v|
        description = ""
        description << "#{v.code}/" if options[:include_code]
        description << v.description
        [description, v.code]
      end
    end

    def lookup_description(name, code, default_value = code)
      refresh_cache if @@description_cache.empty?
      return @@description_cache["#{name}_#{code}"] ||= default_value
    end

    def lookup_description_detail(name, code, default_value = code)
      refresh_cache if @@description_detail_cache.empty?
      return @@description_detail_cache["#{name}_#{code}"] ||= default_value
    end

    def lookup_category(name, code, default_value = code)
      refresh_cache if @@category_cache.empty?
      return @@category_cache["#{name}_#{code}"] ||= default_value
    end

    def keys(name, options={})
      properties = where(:active => true, :name => options[:name].to_s)
      properties = properties.depts_scope(options[:depts]) if options[:depts]
      properties = properties.where(options[:conditions]) if options[:conditions]
      return properties.order("sequence DESC, code").collect { |v| v.code }
    end

    def append(name, code, options={})
      options[:description] = code if options[:description].blank?
      property = find_or_create_by_name_and_code(name, code)
      property.update_attributes(options)
      return property
    end

    def search(filter, options = {})
      application_properties = Kapa::ApplicationProperty.scoped
      if filter.name.present?
        # TODO: A workaround until we remove :academic_period from properties entirely.  (Remove this later.)
        #   Without this conversion to "academic_period", an error on admin/properties/index view would be thrown
        #   if no filters are defined, since the default filter in Kapa::Admin::BaseController sets :name to :term_id.
        if filter.name == "term_id".to_sym
          property_name = "academic_period"
        else
          property_name = filter.name
        end
        application_properties = application_properties.where("name" => property_name)
      end
      application_properties = application_properties.where("active" => filter.active) if filter.active.present?
      return application_properties
    end
  end
end

app/models/kapa/concerns/assessment_criterion.rb
module Kapa::Concerns::AssessmentCriterion
  extend ActiveSupport::Concern

  included do
    self.inheritance_column = nil
    belongs_to :assessment_rubric
    has_many :assessment_scores
    validates_uniqueness_of :criterion, :scope => :assessment_rubric_id
    validates_presence_of :criterion
    before_save :format_fields
  end # included

  def format_fields
    standard.to_s.strip!
    criterion.to_s.strip!
    criterion_desc.to_s.strip!
    criterion_desc.to_s.sub!("\n", "")
  end

  def criterion_detail
    criterion_html
  end
end

app/models/kapa/concerns/assessment_rubric.rb
module Kapa::Concerns::AssessmentRubric
  extend ActiveSupport::Concern

  included do
    attr_accessor :courses, :programs, :transition_points
    has_many :assessment_criterions, -> {order("assessment_criterions.criterion")}, :dependent => :destroy
    validates_presence_of :title
    before_validation :remove_extra_values
    before_save :join_attributes
  end # included

  def remove_extra_values
    remove_values(self.courses)
    remove_values(self.programs)
    remove_values(self.transition_points)
  end

  def join_attributes
    self.course = @courses ? @courses.join(",") : ""
    self.program = @programs ? @programs.join(",") : ""
    self.transition_point = @transition_points ? @transition_points.join(",") : ""
  end

  def effective_term
    "#{Kapa::Term.find(self.start_term_id).description} - #{Kapa::Term.find(self.end_term_id).description}" if self.start_term_id.present? and self.end_term_id.present?
  end

  module ClassMethods
    def search(filter, options = {})
      assessment_rubrics = Kapa::AssessmentRubric.eager_load([:assessment_criterions])
      assessment_rubrics = assessment_rubrics.column_matches(:title => filter.title) if filter.title.present?
      assessment_rubrics = assessment_rubrics.column_contains(:program => filter.program) if filter.program.present?
      assessment_rubrics = assessment_rubrics.column_contains(:course => filter.course) if filter.course.present?
      assessment_rubrics = assessment_rubrics.column_contains(:transition_point => filter.transition_point) if filter.transition_point.present?
      return assessment_rubrics
    end
  end
end

app/models/kapa/concerns/assessment_score.rb
module Kapa::Concerns::AssessmentScore
  extend ActiveSupport::Concern

  included do
    belongs_to :assessment_criterion
    belongs_to :assessment_scorable, :polymorphic => true
  end # included

  module ClassMethods
    def table_for(assessment_rubric, assessment_scorable_type, assessment_scorable_id)
      table = ActiveSupport::OrderedHash.new
      #initialize table first
      for assessment_criterion in assessment_rubric.assessment_criterions
        index = "#{assessment_scorable_id}_#{assessment_criterion.id}"
        table[index] = ""
      end
      #then, fill in scores using ActiveRecord cache.  this is more efficient than filing everything one by one (save SQL execution)
      self.where(["assessment_scorable_type = ? and assessment_scorable_id = ?", assessment_scorable_type, assessment_scorable_id]).each do |s|
        index = "#{s.assessment_scorable_id}_#{s.assessment_criterion_id}"
        table[index] = s.rating if table[index]
      end
      return table
    end
  end
end

app/models/kapa/concerns/contact.rb
module Kapa::Concerns::Contact
  extend ActiveSupport::Concern

  included do
    belongs_to :entity, :polymorphic => true
    validates_presence_of :entity_id
    validates_uniqueness_of :entity_id, :scope => :entity_type, :on => :create, :message => "is already used"
  end # included

  def format
    self.attributes().each_pair do |k, v|
      if v
        self.[]=(k, v.gsub(/\D/, "")) if k =~ /(phone$)/
        self.[]=(k, v.to_s.split(' ').map { |w| w.capitalize }.join(' ')) if k =~ /(street$)|(city$)/
        self.[]=(k, v.to_s.upcase) if k =~ /(state$)/
      end
    end
  end

  def email_alt
    email unless email =~ /^[A-Z0-9_%+-]+@hawaii.edu$/i
  end
end

app/models/kapa/concerns/course_registration.rb
module Kapa::Concerns::CourseRegistration
  extend ActiveSupport::Concern

  included do
    belongs_to :person
    belongs_to :course_offer
    has_many :assessment_scores, :as => :assessment_scorable
  end # included

  def term_desc
    self.course_offer.term_desc
  end

  def subject
    self.course_offer.subject
  end
end

app/views/kapa/layouts/_controls.html.erb
<hr/>
<div class="text-center">

  <% unless local_assigns[:hide_more] %>
    <div class="btn-group">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="glyphicon glyphicon-option-vertical"></span>
      </button>
      <ul class="dropdown-menu">
          <%=yield %>
          <% if local_assigns[:delete_path] and destroy? %>
            <li><%=link_to("Delete", local_assigns[:delete_path], :method => :delete, "data-confirm" => "Are you sure you want to delete?") %></li>
          <% end %>
      </ul>
    </div>
  <% end %>

  <% unless local_assigns[:hide_cancel] %>
    <%=button_to_link "Cancel", request.fullpath, "data-confirm" => "Are you sure you want to discard changes?", :icon => "glyphicon-ban-circle" %>
  <% end %>

  <% unless local_assigns[:hide_update] or local_assigns[:hide_save] %>
    <button class="btn btn-primary" name="commit" type="submit"><span class="glyphicon glyphicon-ok-circle" aria-hidden="true"></span> <%=local_assigns[:save_text] || "Save" %></button>
  <% end %>

</div>

app/views/kapa/layouts/_menu.html.erb
<%
 if @current_user
   menu_items = {}
   menu_items["Document"] = []
   menu_items["Document"].push ["Files", kapa_files_path] if read?(:kapa_files)
   menu_items["Document"].push ["Forms", kapa_forms_path] if read?(:kapa_forms)
   menu_items["Document"].push ["Letters", kapa_texts_path] if read?(:kapa_texts)
   menu_items["Administration"] = []
   menu_items["Administration"].push ["Form Builder", kapa_form_templates_path] if manage?(:kapa_form_templates)
   menu_items["Administration"].push ["Letter Templates", kapa_text_templates_path] if manage?(:kapa_text_templates)
   menu_items["Administration"].push ["Properties", kapa_properties_path] if manage?(:kapa_properties)
   menu_items["Administration"].push ["Users", kapa_users_path] if manage?(:kapa_users)
 end
%>

<% menu_items.each_pair do |menu, items| %>
  <% if items.present? %>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%=menu %><b class="caret"></b></a>
      <ul class="dropdown-menu">
        <% for item in items %>
          <%=content_tag :li, link_to(item[0], item[1]) %>
        <% end %>
      </ul>
    </li>
  <% end %>
<% end %>

app/views/kapa/layouts/_modal.html.erb
<div class="modal fade" id="<%=modal_id%>" tabindex="-1" role="dialog" aria-labelledby="modal_label" aria-hidden="true">
  <div class="modal-dialog <%=modal_class if local_assigns[:modal_class] %>">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="modal_label"><%=modal_title%></h4>
      </div>
      <div class="modal-body">
        <%=yield%>
      </div>
      <div class="modal-footer">
        <% if local_assigns[:modal_form_id] and modal_form_id == "filter_form" %>
          <div class="pull-left">
            <%=button_to_link "Clear", {:clear_filter => true}, :icon => "glyphicon-remove", :class => "btn btn-warning", :data => {:confirm => "Are you sure you want to clear search fields?"} %>
          </div>
        <% end %>
        <button type="button" id="modal_close" class="btn btn-default" data-dismiss="modal">Close</button>
        <% if local_assigns[:modal_form_id] %>
          <button type="button" id="modal_submit" class="btn btn-primary" data-submit="#<%=modal_form_id%>">OK</button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/kapa/layouts/kapa.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%=content_for?(:title) ? yield(:title) : t(:kapa_brand) %></title>
  <%=csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <%=stylesheet_link_tag "kapa/kapa", :media => "all" %>
  <%=stylesheet_link_tag "application", :media => "all" %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%#= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%#= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%#= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%#= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%#= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

  <%=javascript_include_tag "kapa/kapa" %>
  <%=javascript_include_tag "application" %>
  <%=yield :head %>
</head>
<body>

<div class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
    <%=link_to t(:kapa_brand), kapa_root_path, :class => "navbar-brand" %>

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#menu" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </div>

    <div class="navbar-collapse collapse navbar-responsive-collapse" id="menu">
      <% if @current_user %>
        <ul class="nav navbar-nav">
          <%=render :partial => "kapa/layouts/menu", :locals => {:current_user => @current_user} %>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <%= bootstrap_form_for(:filter, :url => kapa_persons_path, :html => {:method => :get, :class => "navbar-form navbar-left", :role => "search"}) do |f| %>
            <div class="input-group">
              <input name="filter[key]" type="text" class="form-control" placeholder = "Search Person" data-toggle = "tooltip" data-placement = "bottom" title = "ID, Name, Email, or Phone" value="<%=@filter.key if @filter %>">
              <%=f.hidden_field :limit, :value => 10 %>
              <div class="input-group-btn">
                <button type="submit" class="btn btn-default">
                  <i class="glyphicon glyphicon-search" aria-hidden="true"></i>
                </button>
              </div>
            </div>
          <% end if read? :kapa_persons and access_dept?(:kapa_persons) %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><strong><%=@current_user.uid %></strong> <b class="caret"></b></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li><%= link_to "Logout", kapa_user_session_path, {:method => :delete} %></li>
            </ul>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
</div>

<% if Kapa.beta? %><div class="alert alert-warning" role="alert">This is a beta system.  Any changes made this database system will be wiped periodically.  Please use for testing and/or training purposes only.</div><% end %>

<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <%=bootstrap_flash %>
    </div>
  </div>
  <% if content_for?(:box1) %>
    <div class="row">
      <div class="well col-lg-12">
      <%=yield :box1 %>
      </div>
    </div>
  <% end %>

  <% if content_for?(:box2) %>
    <div class="row">
      <div class="well col-lg-12">
        <%=yield :box2 %>
      </div>
    </div>
  <% end %>

  <% if content_for?(:dialog) %>
    <%=yield :dialog %>
  <% end %>

  <footer>
    <p class="text-center"><%=t :kapa_footer_html, :year => Date.today.year%></p>
  </footer>

</div>

</body>
</html>

app/views/kapa/layouts/letter.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>PDF</title>
  <%= wicked_pdf_stylesheet_link_tag "pdf" %>
</head>
<body>
  <div class="row header">
    <div class="col-xs-6">
      <%#=image_tag t(:kapa_pdf_header), :width => "200px" %>
    </div>
    <div class="col-xs-6 text-right">College of Education<br>
      <strong>
        <% if @dept == "OSAS" %>
          Office of Student Academic Services
        <% elsif@dept == "SPED" %>
          Department of Special Education
        <% end %>
      </strong>
    </div>
  </div>

  <%= yield %>

  <div class="text-right footer">
    <% if @dept == "OSAS" %>
      <p>
        1776 University Ave. <br/>
        Everly Hall Room 126<br/>
        Honolulu, HI 96822<br/>
        Telephone: 808-956-7915 or 808-956-7849
      </p>
    <% elsif @dept == "SPED" %>
      <p>
        1776 University Ave. <br/>
        West Hall Room 120<br/>
        Honolulu, HI 96822<br/>
        Telephone: 808-956-4345
      </p>
    <% end %>  
  </div>
</body>
</html>