config/routes.rb
Rails.application.routes.draw do

  extra_actions = Proc.new do
    collection do
      get :export
      post :import
      get :summarize
    end
  end

  namespace :kapa do
    root :to => 'user_sessions#show', :as => :root
    get '/logout' => 'user_sessions#destroy', :as => :logout
    get '/error' => 'user_sessions#error', :as => :error
    get '/cas' => 'user_sessions#cas', :as => :cas
    get 'user_session/validate' => 'user_sessions#validate'
    resource :user_session
    get 'persons/lookup(/:id)' => 'persons#lookup', :as => :persons_lookup
    get 'persons/sync(/:id)' => 'persons#sync', :as => :persons_sync
    resources :persons, &extra_actions
    resources :files, &extra_actions
    resources :forms, &extra_actions
    resources :form_templates, &extra_actions
    resources :form_template_fields, &extra_actions
    resources :texts, &extra_actions
    resources :text_templates, &extra_actions
    get 'text_templates/preview(/:id)' => 'text_templates#preview', :as => :text_templates_preview
    resources :contents, &extra_actions
    resources :properties, &extra_actions
    resources :users, &extra_actions
    resources :user_assignments, &extra_actions
  end

  #catch-all route for 404 (not found) requests
  match '*path', via: :all, to: 'application#error_404' , constraints: lambda { |request|
    !request.path.match? /^(\/rails)/
  }
end

app/models/kapa/application_property_base.rb
module Kapa::ApplicationPropertyBase
  extend ActiveSupport::Concern

  included do
    self.table_name = :properties
    validates_uniqueness_of :code, :scope => :name
    validates_presence_of :name, :code
  end

  class_methods do
    @@description_cache = HashWithIndifferentAccess.new
    @@description_detail_cache = HashWithIndifferentAccess.new
    @@category_cache = HashWithIndifferentAccess.new

    def refresh_cache
      @@description_cache.clear
      Kapa::ApplicationProperty.all.each { |v| @@description_cache["#{v.name}_#{v.code}"] = v.description }
      @@description_detail_cache.clear
      Kapa::ApplicationProperty.all.each { |v| @@description_detail_cache["#{v.name}_#{v.code}"] = v.description_short }
      @@category_cache.clear
      Kapa::ApplicationProperty.all.each { |v| @@category_cache["#{v.name}_#{v.code}"] = v.category }
    end

    def selections(options = {})
      properties = where(:active => true, :name => options[:name].to_s)
      properties = properties.depts_scope(options[:depts]) if options[:depts]
      properties = properties.where(options[:conditions]) if options[:conditions]
      properties.order("sequence DESC, description").collect do |v|
        description = ""
        description << "#{v.code}/" if options[:include_code]
        description << v.description
        [description, v.code]
      end
    end

    def lookup_description(name, code, default_value = code)
      refresh_cache if @@description_cache.empty?
      return @@description_cache["#{name}_#{code}"] ||= default_value
    end

    def lookup_description_detail(name, code, default_value = code)
      refresh_cache if @@description_detail_cache.empty?
      return @@description_detail_cache["#{name}_#{code}"] ||= default_value
    end

    def lookup_category(name, code, default_value = code)
      refresh_cache if @@category_cache.empty?
      return @@category_cache["#{name}_#{code}"] ||= default_value
    end

    def keys(name, options={})
      properties = where(:active => true, :name => options[:name].to_s)
      properties = properties.depts_scope(options[:depts]) if options[:depts]
      properties = properties.where(options[:conditions]) if options[:conditions]
      return properties.order("sequence DESC, code").collect { |v| v.code }
    end

    def append(name, code, options={})
      options[:description] = code if options[:description].blank?
      property = find_or_create_by_name_and_code(name, code)
      property.update_attributes(options)
      return property
    end

    def search(filter, options = {})
      application_properties = Kapa::ApplicationProperty.all
      application_properties = application_properties.where("name" => filter.name)  if filter.name.present?
      application_properties = application_properties.where("active" => filter.active) if filter.active.present?
      return application_properties
    end
  end
end

app/models/kapa/assessment_score_base.rb
module Kapa::AssessmentScoreBase
  extend ActiveSupport::Concern

  included do
    belongs_to :assessment_criterion
    belongs_to :assessment_scorable, :polymorphic => true
  end

  def rating_desc
    if self.assessment_criterion.type == "select" and self.assessment_criterion.type_option
      return Kapa::Property.lookup_description(assessment_criterion.type_option, self.rating)
    else
      return self.rating
    end
  end

  class_methods do
    def scores(assessment_scorables, assessment_rubric)
      #initialize table first
      scores = ActiveSupport::OrderedHash.new
      assessment_scorables.each do |s|
        assessment_rubric.active_criterions.each do |c|
          index = "#{s.id}_#{c.id}"
          scores[index] = ""
        end
      end
      #then, fill in scores using ActiveRecord cache.  this is more efficient than filing everything one by one (save SQL execution)
      self.where(:assessment_scorable_type => assessment_scorables.first.class, :assessment_scorable_id => assessment_scorables.collect {|s| s.id}).each do |score|
        index = "#{score.assessment_scorable_id}_#{score.assessment_criterion_id}"
        scores[index] = score.rating if scores[index]
      end
      return scores
    end
  end
end

app/models/kapa/bulk_message.rb
class Kapa::BulkMessage < Kapa::KapaModel
  include Kapa::BulkMessageBase
end

app/models/kapa/bulk_message_base.rb
module Kapa::BulkMessageBase
  extend ActiveSupport::Concern

  included do
    has_many :messages
    belongs_to :message_template

    after_create :set_default_contents, :replace_variables
  end

  def set_default_contents
    if self.message_template.present?
      self.name = self.message_template.title
      self.body = self.message_template.body
      self.save
    end
  end

  def replace_variables
  end

  def send_messages
    person_ids = Kapa::ContactList.where(:id => self.ext.contact_list_ids).map(&:person_ids) + self.ext.person_ids
    persons = Kapa::Person.where(:id => person_ids.flatten.uniq)
    persons.each do |person|
      message = person.messages.build(self.attributes.slice("name", "subject", "body", "message_template_id"))
      message.bulk_message = self
      message.save
    end
  end
end

app/models/kapa/calendar_event.rb
class Kapa::CalendarEvent < Kapa::KapaModel
  include Kapa::CalendarEventBase
end

app/models/kapa/calendar_event_base.rb
module Kapa::CalendarEventBase
  extend ActiveSupport::Concern

  included do
    belongs_to :person
  end
end

app/models/kapa/concerns/advising_session.rb
module Kapa::Concerns::AdvisingSession
  extend ActiveSupport::Concern

  included do
    belongs_to :person
    belongs_to :template
    has_one :contact, :as => :entity
    has_many :advising_actions
    belongs_to :user_primary,
               :class_name => "User",
               :foreign_key => "user_primary_id"
    belongs_to :user_secondary,
               :class_name => "User",
               :foreign_key => "user_secondary_id"
    validates_presence_of :person_id, :session_date, :session_type
  end # included

  def name
    if anonymous?
      return "#{identity_note}*"
    else
      return self.person.full_name
    end
  end

  def anonymous?
    return person_id == 0
  end

  module ClassMethods
    def search(filter, options = {})
      advising_sessions = Kapa::AdvisingSession.eager_load([:person => :contact])
      advising_sessions = advising_sessions.where(:session_date => filter.date_start..filter.date_end) if filter.date_start.present? and filter.date_end.present?
      advising_sessions = advising_sessions.where(:task => filter.task) if filter.task.present?
      advising_sessions = advising_sessions.where(:interest => filter.interest) if filter.interest.present?
      advising_sessions = advising_sessions.assigned_scope(filter.user_id) if filter.user_id.present?

      case filter.user.access_scope
        when 3
          # Do nothing
        when 2
          advising_sessions = advising_sessions.depts_scope(filter.user.depts)
        when 1
          advising_sessions = advising_sessions.assigned_scope(filter.user.id)
        else
          advising_sessions = advising_sessions.where("0 = 1")
      end
      return advising_sessions
    end

    def to_csv(filter, options = {})
      advising_sessions = self.search(filter).order("session_date DESC, advising_sessions.id DESC")
      CSV.generate do |csv|
        csv << self.csv_columns
        advising_sessions.each do |c|
          csv << self.csv_row(c)
        end
      end
    end

    def csv_columns
      [:id_number,
       :last_name,
       :first_name,
       :cur_street,
       :cur_city,
       :cur_state,
       :cur_postal_code,
       :cur_phone,
       :email,
       :session_date,
       :session_type,
       :task,
       :classification,
       :interest,
       :location,
       :handled_by]
    end

    def csv_row(c)
      [c.rsend(:person, :id_number),
       c.rsend(:person, :last_name),
       c.rsend(:person, :first_name),
       c.rsend(:person, :contact, :cur_street),
       c.rsend(:person, :contact, :cur_city),
       c.rsend(:person, :contact, :cur_state),
       c.rsend(:person, :contact, :cur_postal_code),
       c.rsend(:person, :contact, :cur_phone),
       c.rsend(:person, :contact, :email),
       c.rsend(:session_date),
       c.rsend(:session_type),
       c.rsend(:task),
       c.rsend(:classification),
       c.rsend(:interest),
       c.rsend(:location),
       c.rsend(:handled_by)]
    end

  end
end

app/models/kapa/concerns/application_property.rb
module Kapa::Concerns::ApplicationProperty
  extend ActiveSupport::Concern

  included do
    self.table_name = :properties
    validates_uniqueness_of :code, :scope => :name
    validates_presence_of :name, :code
  end # included

  module ClassMethods
    @@description_cache = HashWithIndifferentAccess.new
    @@description_detail_cache = HashWithIndifferentAccess.new
    @@category_cache = HashWithIndifferentAccess.new

    def refresh_cache
      @@description_cache.clear
      Kapa::ApplicationProperty.all.each { |v| @@description_cache["#{v.name}_#{v.code}"] = v.description }
      @@description_detail_cache.clear
      Kapa::ApplicationProperty.all.each { |v| @@description_detail_cache["#{v.name}_#{v.code}"] = v.description_short }
      @@category_cache.clear
      Kapa::ApplicationProperty.all.each { |v| @@category_cache["#{v.name}_#{v.code}"] = v.category }
    end

    def selections(options = {})
      properties = where(:active => true, :name => options[:name].to_s)
      properties = properties.depts_scope(options[:depts]) if options[:depts]
      properties = properties.where(options[:conditions]) if options[:conditions]
      properties.order("sequence DESC, description").collect do |v|
        description = ""
        description << "#{v.code}/" if options[:include_code]
        description << v.description
        [description, v.code]
      end
    end

    def lookup_description(name, code, default_value = code)
      refresh_cache if @@description_cache.empty?
      return @@description_cache["#{name}_#{code}"] ||= default_value
    end

    def lookup_description_detail(name, code, default_value = code)
      refresh_cache if @@description_detail_cache.empty?
      return @@description_detail_cache["#{name}_#{code}"] ||= default_value
    end

    def lookup_category(name, code, default_value = code)
      refresh_cache if @@category_cache.empty?
      return @@category_cache["#{name}_#{code}"] ||= default_value
    end

    def keys(name, options={})
      properties = where(:active => true, :name => options[:name].to_s)
      properties = properties.depts_scope(options[:depts]) if options[:depts]
      properties = properties.where(options[:conditions]) if options[:conditions]
      return properties.order("sequence DESC, code").collect { |v| v.code }
    end

    def append(name, code, options={})
      options[:description] = code if options[:description].blank?
      property = find_or_create_by_name_and_code(name, code)
      property.update_attributes(options)
      return property
    end

    def search(filter, options = {})
      application_properties = Kapa::ApplicationProperty.scoped
      if filter.name.present?
        # TODO: A workaround until we remove :academic_period from properties entirely.  (Remove this later.)
        #   Without this conversion to "academic_period", an error on admin/properties/index view would be thrown
        #   if no filters are defined, since the default filter in Kapa::Admin::BaseController sets :name to :term_id.
        if filter.name == "term_id".to_sym
          property_name = "academic_period"
        else
          property_name = filter.name
        end
        application_properties = application_properties.where("name" => property_name)
      end
      application_properties = application_properties.where("active" => filter.active) if filter.active.present?
      return application_properties
    end
  end
end

app/models/kapa/concerns/assessment_criterion.rb
module Kapa::Concerns::AssessmentCriterion
  extend ActiveSupport::Concern

  included do
    self.inheritance_column = nil
    belongs_to :assessment_rubric
    has_many :assessment_scores
    validates_uniqueness_of :criterion, :scope => :assessment_rubric_id
    validates_presence_of :criterion
    before_save :format_fields
  end # included

  def format_fields
    standard.to_s.strip!
    criterion.to_s.strip!
    criterion_desc.to_s.strip!
    criterion_desc.to_s.sub!("\n", "")
  end

  def criterion_detail
    criterion_html
  end
end

app/models/kapa/concerns/assessment_rubric.rb
module Kapa::Concerns::AssessmentRubric
  extend ActiveSupport::Concern

  included do
    attr_accessor :courses, :programs, :transition_points
    has_many :assessment_criterions, -> {order("assessment_criterions.criterion")}, :dependent => :destroy
    validates_presence_of :title
    before_validation :remove_extra_values
    before_save :join_attributes
  end # included

  def remove_extra_values
    remove_values(self.courses)
    remove_values(self.programs)
    remove_values(self.transition_points)
  end

  def join_attributes
    self.course = @courses ? @courses.join(",") : ""
    self.program = @programs ? @programs.join(",") : ""
    self.transition_point = @transition_points ? @transition_points.join(",") : ""
  end

  def effective_term
    "#{Kapa::Term.find(self.start_term_id).description} - #{Kapa::Term.find(self.end_term_id).description}" if self.start_term_id.present? and self.end_term_id.present?
  end

  module ClassMethods
    def search(filter, options = {})
      assessment_rubrics = Kapa::AssessmentRubric.eager_load([:assessment_criterions])
      assessment_rubrics = assessment_rubrics.column_matches(:title => filter.title) if filter.title.present?
      assessment_rubrics = assessment_rubrics.column_contains(:program => filter.program) if filter.program.present?
      assessment_rubrics = assessment_rubrics.column_contains(:course => filter.course) if filter.course.present?
      assessment_rubrics = assessment_rubrics.column_contains(:transition_point => filter.transition_point) if filter.transition_point.present?
      return assessment_rubrics
    end
  end
end

app/models/kapa/concerns/assessment_score.rb
module Kapa::Concerns::AssessmentScore
  extend ActiveSupport::Concern

  included do
    belongs_to :assessment_criterion
    belongs_to :assessment_scorable, :polymorphic => true
  end # included

  module ClassMethods
    def table_for(assessment_rubric, assessment_scorable_type, assessment_scorable_id)
      table = ActiveSupport::OrderedHash.new
      #initialize table first
      for assessment_criterion in assessment_rubric.assessment_criterions
        index = "#{assessment_scorable_id}_#{assessment_criterion.id}"
        table[index] = ""
      end
      #then, fill in scores using ActiveRecord cache.  this is more efficient than filing everything one by one (save SQL execution)
      self.where(["assessment_scorable_type = ? and assessment_scorable_id = ?", assessment_scorable_type, assessment_scorable_id]).each do |s|
        index = "#{s.assessment_scorable_id}_#{s.assessment_criterion_id}"
        table[index] = s.rating if table[index]
      end
      return table
    end
  end
end

app/models/kapa/concerns/contact.rb
module Kapa::Concerns::Contact
  extend ActiveSupport::Concern

  included do
    belongs_to :entity, :polymorphic => true
    validates_presence_of :entity_id
    validates_uniqueness_of :entity_id, :scope => :entity_type, :on => :create, :message => "is already used"
  end # included

  def format
    self.attributes().each_pair do |k, v|
      if v
        self.[]=(k, v.gsub(/\D/, "")) if k =~ /(phone$)/
        self.[]=(k, v.to_s.split(' ').map { |w| w.capitalize }.join(' ')) if k =~ /(street$)|(city$)/
        self.[]=(k, v.to_s.upcase) if k =~ /(state$)/
      end
    end
  end

  def email_alt
    email unless email =~ /^[A-Z0-9_%+-]+@hawaii.edu$/i
  end
end

app/models/kapa/concerns/course_registration.rb
module Kapa::Concerns::CourseRegistration
  extend ActiveSupport::Concern

  included do
    belongs_to :person
    belongs_to :course_offer
    has_many :assessment_scores, :as => :assessment_scorable
  end # included

  def term_desc
    self.course_offer.term_desc
  end

  def subject
    self.course_offer.subject
  end
end

app/views/kapa/publications/_publication_form.html.erb
<% content_for(:dialog) do %>
  <%= render :layout => '/kapa/layouts/modal', :locals => {:modal_id => "change_publication_type_dialog", :modal_title => "Change Publication Type", :modal_form_id => "change_publication_type_form" } do %>
    <%= bootstrap_form_for(:publication, :url => kapa_publication_path(:id => @publication), :html => {:method => :put, :id => "change_publication_type_form"}) do |t| %>
      <%= f.property_select :pubtype, :name => :publication_type, :label => "Publication Type" %>
    <% end %>
  <% end %>
<% end %>

<%= bootstrap_fields_for :publication do |f| %>

  <div class="row">
    <div class="col-sm-4">
      <div class="form-group">
        <%= label :pubtype, :description, "Publication Type" %>
        <p class="form-control-static"><span><%= Kapa::Property.lookup_description(:publication_type, @publication.pubtype) %></span>
          <% if @current_user.manage? %>
            <button type="button" class="btn btn-default btn-xs" data-toggle="modal" data-target="#change_publication_type_dialog"><span class="glyphicon glyphicon-pencil"></span></button>
          <% end %>
        </p>
      </div>

      <%= f.text_field :l, :label => "Research Location", :placeholder => "Honolulu" %>
      <%= f.text_field :o, :label => "Institution", :placeholder => "College of Education, University of Hawaii at Manoa" %>
      <%= f.text_field :ou, :label => "Department" %>

      <%= f.text_field :pubtitle, :label => "Title" %>
      <div class="form-group">
        <%= label_tag "publication_pubdate", "Date" %>
        <%= date_picker :publication, :pubdate %>
      </div>

      <%= f.text_field :documentlocation, :label => "Document URL" %>
      <%= f.text_field :documentidentifier, :label => "Document Identifier" %>
      <span id="documentidentifier_help" class="help-block">
        The DOI or ISBN number for publications that have one, e.g. 978-1412957465 (13-digit ISBN), 141295746X (10-digit ISBN), or 10.1007/BF02504547 (DOI).
      </span>
    </div>

    <div class="col-sm-4">
      <% if @publication.pubtype == "book" %>
        <!-- Book -->
        <%= f.text_field :pubvol, :label => "Volume" %>
        <%= f.text_field :pubnumofvol, :label => "Number of Volumes" %>
        <%= f.text_field :pubpages, :label => "Pages" %>
        <%= f.text_field :pubpublisher, :label => "Publisher" %>
        <%= f.text_field :publocation, :label => "Publisher Location" %>
        <%= f.text_field :pubeditor, :label => "Editor" %>
        <%= f.text_field :pubedition, :label => "Edition" %>

      <% elsif @publication.pubtype == "book_chapter" %>
        <!-- Book Chapter -->
        <%= f.text_field :pubvol, :label => "Volume" %>
        <%= f.text_field :pubnumofvol, :label => "Number of Volumes" %>
        <%= f.text_field :pubpages, :label => "Pages" %>
        <%= f.text_field :pubbooktitle, :label => "Book Title" %>
        <%= f.text_field :pubbookchapter, :label => "Book Chapter" %>
        <%= f.text_field :pubpublisher, :label => "Publisher" %>
        <%= f.text_field :publocation, :label => "Publisher Location" %>
        <%= f.text_field :pubeditor, :label => "Editor" %>
        <%= f.text_field :pubedition, :label => "Edition" %>

      <% elsif @publication.pubtype == "conference_proceedings" %>
        <!-- Conference Proceedings -->
        <%= f.text_field :pubvol, :label => "Volume" %>
        <%= f.text_field :pubpages, :label => "Pages" %>
        <%= f.text_field :pubvenue, :label => "Conference Name" %>
        <%= f.text_field :publocation, :label => "Conference Location" %>
        <%= f.text_field :puborganization, :label => "Society/Organization running conference" %>

      <% elsif @publication.pubtype == "journal_article" %>
        <!-- Journal Article -->
        <%= f.text_field :pubvol, :label => "Volume" %>
        <%= f.text_field :pubpages, :label => "Pages" %>
        <%= f.text_field :pubvenue, :label => "Journal Name" %>
        <%= f.text_field :pubpublisher, :label => "Publisher" %>
        <%= f.text_field :puborganization, :label => "Organization/Society publishing journal" %>

      <% elsif @publication.pubtype == "multimedia_contribution" %>
        <!-- Multimedia Contribution -->
        <%= f.text_field :pubvol, :label => "Volume" %>
        <%= f.text_field :pubpublisher, :label => "Publisher" %>

      <% elsif @publication.pubtype == "presentation" %>
        <!-- Presentation -->
        <%= f.text_field :pubvenue, :label => "Event at which presented" %>
        <%= f.text_field :publocation, :label => "Location of presentation" %>
        <%= f.text_field :puborganization, :label => "Organization presented to" %>

      <% elsif @publication.pubtype == "report" %>
        <!-- Report -->
        <%= f.text_field :pubpublisher, :label => "Publisher" %>
        <%= f.text_field :publocation, :label => "Publisher Location" %>
        <%= f.text_field :pubpages, :label => "Pages" %>

      <% end %>

      <%= f.text_field :pubkeyword, :label => "Keywords" %>
      <span id="pubkeyword_help" class="help-block">
        list of keywords, separated by commas
      </span>
      <%= f.text_area :pubcontributor, :label => "Authors" %>
      </span>
    </div>

    <div class="col-sm-4">
      <% if @publication.thumbnail.exists? %>
        <p>
          You have already uploaded a cover image named <strong><%= @publication.thumbnail_file_name %></strong>. To replace it, choose a new file below.
        </p>
      <% end %>
      <%= f.file_field :thumbnail, :label => "Cover image" %>
      <span id="thumbnail_help" class="help-block">
        <p>
          Any representative image appropriate to the publication, in .jpg or .png format.
        </p>
        <p>
          Examples include presentation photos, book covers, or conference logos. An image is required when featuring this publication on our website.
        </p>
      </span>
      <%= f.text_area :pubabstract, {:label => "Abstract", :cols => 54, :rows => 20} %>
      <%= f.hidden_field :person_id  %>
    </div>
  </div>
</div>

<% end %>

app/views/kapa/publications/index.html.erb
<% content_for(:dialog) do %>

  <%= render :layout => '/kapa/layouts/modal', :locals => {:modal_id => "filter_dialog", :modal_title => "Search", :modal_form_id => "filter_form"} do %>
    <%= bootstrap_form_for(:filter, :url => kapa_publications_path, :html => {:method => :get, :id => "filter_form"}) do |f| %>
      <div class="row">
        <div class="col-sm-6">
          <%= f.text_field :pubtitle, :label => "Title" %>
          <%= f.property_select :pubtype, :name => :publication_type, :label => "Type", :include_blank => "Any" %>
          <%= f.text_field :keyword, :label => "Keyword" %>
          <%= f.text_field :author, :label => "Author" %>
        </div>
        <div class="col-sm-6">
          <div class="form-group">
            <%= label_tag "filter_date_start", "Publication Date Start" %>
            <%= date_picker :filter, :pubdate_start %>
          </div>
          <div class="form-group">
            <%= label_tag "filter_date_end", "Publication Date End" %>
            <%= date_picker :filter, :pubdate_end %>
          </div>
          <%= f.select :per_page, [10, 20, 30, 40, 50] %>
        </div>
      </div>
    <% end %>
  <% end %>

<% end %>

<% content_for(:box1) do %>

  <h3>Publications</h3>

  <div class="row">
    <div class="col-sm-12 text-right">
      <%=bootstrap_button "Download", {:action => :export}, :icon => "glyphicon-download" %>
      <%=bootstrap_button "Search", nil, "data-toggle" => "modal", "data-target" => "#filter_dialog", :icon => "glyphicon-search" %>
    </div>
  </div>

  <table id="advising_list" class="table table-striped">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Type</th>
        <th>Title</th>
        <th>Date</th>
        <th>Authors</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% for publication in @publications %>
        <tr>
          <td><%= publication.person.id_number %></td>
          <td><%= link_to abbr(publication.person.full_name), kapa_person_path(:id => publication.person_id) if publication.person %></td>
          <td><%= Kapa::Property.lookup_description(:publication_type, publication.pubtype) %>
          <td><%= abbr publication.pubtitle, 25 %></td>
          <td><%= publication.pubdate %></td>
          <td><%= abbr publication.pubcontributor, 25 %></td>
          <td class="right"><%=link_to "Show", {:action => :show, :id => publication}, :class => "btn btn-default btn-xs" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="text-center"><%=will_paginate @publications, :renderer => BootstrapPagination::Rails %></div>

<% end %>

app/views/kapa/publications/new.html.erb
<% content_for(:box1) do %>
  <%= render :partial => "/kapa/persons/person_detail" %>

  <h4 class="section-header divider">
    <%= link_to "", kapa_person_path(:id => @person), :class => "glyphicon glyphicon-chevron-left" %>
    New Publication
  </h4>

  <div class="row">
    <div class="col-sm-8">
      <%= bootstrap_form_for :publication, :url => kapa_publications_path(:id => @person) do |f| %>
        <%= f.property_select :pubtype, :name => :publication_type, :label => "Publication Type" %>
        <%= render :partial => "/kapa/layouts/controls" if @current_user.write? %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/kapa/publications/show.html.erb
<% content_for(:box1) do %>
  <%= render :partial => "/kapa/persons/person_detail" %>

  <h4 class="section-header divider">
    <%= link_to "", kapa_person_path(:id => @person, :anchor => :publications), :class => "glyphicon glyphicon-chevron-left" %>
    Publications
  </h4>

  <div>
    <%= bootstrap_form_for :publication, :url => kapa_publication_path(:id => @publication), :html => {:method => :put, :multipart => true} do |f| %>
      <%= render :partial => "publication_form", :locals => {:f => f} %>
      <%= render :partial => "/kapa/layouts/controls" if @current_user.write? %>
    <% end %>
  </div>
<% end %>